### ISSUE TITLE
Static build

### ISSUE THREAD

**Issue by Br3nda** [WhareHauora/App#110]
Is there a command to build to a static file? 

I saw this is using next which looks like a serverside framework - does this needs a server to run on? or can it be built to a clientside only file?

**Comment by Br3nda** [comment]
Talked to Megan. The thing I'm looking for is webpack.

**Comment by MeghanHughes** [comment]
Hey @Br3nda this should be good to go now. Do you want us to see if it hooks up to gitpages, or do you?

**Comment by Br3nda** [comment]
Whoever gets to it first :)

**Comment by Br3nda** [comment]
i'm setting this up and assuming the command i want is `npm run build`

**Comment by Br3nda** [comment]
i've been trying `next build` and `next export`. neither make any html files i can see. Is there a way to get one? without one how does the browser know what javascript to start? Any clue please.
`next build` was in the package.json
`next export` is mentioned in the page @janie-t linked to here.

**Comment by Br3nda** [comment]
Also seeing this

```
$ npm run build

> whare-hauora@1.0.0 build /home/brenda/projects/wharehauora-app
> next export

> using build directory: /home/brenda/projects/wharehauora-app/.next
  copying "static" directory
  copying "static build" directory
> No "exportPathMap" found in "next.config.js". Generating map from "./pages"
> exporting path: /account
TypeError: Cannot read property 'id' of undefined
    at /home/brenda/projects/wharehauora-app/.next/dist/bundles/pages/account.js:1360:39
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)

```

**Comment by MeghanHughes** [comment]
Hmmm - I am looking into this now @Br3nda I have getting an error `command not found: next` when I run `next build` which is odd to me. @iainkirkpatrick might have an immediate remedy..?

**Comment by MeghanHughes** [comment]
https://github.com/zeit/next.js/#static-html-export

**Comment by MeghanHughes** [comment]
`Could not find a valid build in the '.next' directory! Try building your app with 'next build' before starting the server.`
but `next build` returns error `command next not found` even thought it is included in script:
```  "scripts": {
    "dev": "node server.js",
    "build": "next build && next export",
    "start": "NODE_ENV=production node server.js",
    "test": "ava test/**/*.js --serial --verbose"
  },```

Have tried to delete `node_modules` folder and `.next` folder and `npm i` but same error.

**Comment by MeghanHughes** [comment]
(in relation to @Br3nda error message - I can't even get that far at the moment) according to the docs we need to add our version of

```module.exports = {
  exportPathMap: async function (defaultPathMap) {
    return {
      '/': { page: '/' },
      '/about': { page: '/about' },
      '/readme.md': { page: '/readme' },
      '/p/hello-nextjs': { page: '/post', query: { title: 'hello-nextjs' } },
      '/p/learn-nextjs': { page: '/post', query: { title: 'learn-nextjs' } },
      '/p/deploy-nextjs': { page: '/post', query: { title: 'deploy-nextjs' } }
    }
  }
}``` 

into the `next.config.js`

which would be, I think: 

```module.exports = {
  exportPathMap: async function (defaultPathMap) {
    return {
      '/': { page: '/' },
      '/dashboard: { page: '/dashboard' },
      '/room/:id': { page: '/room', query: { id } }
    }
  }
}```

**Comment by iainkirkpatrick** [comment]
hey all - i get the same error as @Br3nda when running `next export`, looks to me like the `account` page is erroring when trying to generate the static output (not really sure why, the only use of `.id` is on L44 of `pages/account` and it's inside an async function?) - might take some investigation to figure out why it's erroring. But running `npm run build` is working for me, so it's weird yours isn't @MeghanHughes ? The latest I have from branch `mh/reinstateSW` doesn't have an npm script for exporting, so i used npx and ran `npx next export` after running `npm run build`.

Reading back through this thread tho, and at the moment the app is expecting to have a server deployed somewhere to make requests to - both for the service worker and registering / unregistering for push notifications. Is it ideal to build the app statically so it can be hosted somewhere like Github Pages? If so then it looks to me like we'd need to think about how to load the service worker (i think i've read it can be done from the static folder with some figuring out of pathing to assets), but also how to handle push notifications... my latest understanding was that we would try having the node server make frequent requests to the ruby API server for room-by-room data, and 'push' notifications to clients from the node server?

sorry that's a bit of a wall of text!

**Comment by MeghanHughes** [comment]
Alternatively, we can deploy to heroku instead of Github Pages?? Then we don't have to worry about doing a static build? @Br3nda?
We already have a deployment setup for the app through Heroku, though at the moment it is only deploying the service worker branch for PWA auditing.

**Comment by Br3nda** [comment]
Could we be missing some `.env`?

**Comment by Br3nda** [comment]
I'm very keen to get it compiling to plain files and not needing a process running. Then we have options on how we deploy it.

**Comment by Br3nda** [comment]
@iainkirkpatrick `npm run build` doesn't produce errors. But it doesn't produce any html either. Or, i can't find any. It does make js and css and map files.

**Comment by iainkirkpatrick** [comment]
@Br3nda @MeghanHughes  `npm run build` should just build the server + client-side bundle for a deployment, for exporting a static build we need to `npm run build` and then `npx next export` (we could have an npm script set up for this).

When I try this this morning though I get the same error you encountered above regarding `Cannot read property 'id' of undefined` in `account.js`. I'm aiming to work on Whare Hauora today so I can try and suss out what's going on there if that's helpful...

**Comment by janie-t** [comment]
npm run build   THEN npm run export = creates a static build folder called "Out" which you can upload to a static host site. e.g. callous-flower.surge.sh

**Comment by janie-t** [comment]
I was able to build this from the current Development branch.  the npm run build, then npm run export creates a build folder called 'out'
