### ISSUE TITLE
Whare & rooms > Add Room Form > When submitted creates a new room

### ISSUE THREAD

**Issue by janie-t** [WhareHauora/App#139]
The form needs to submit to database and create a new room

**Comment by MeghanHughes** [comment]
@Br3nda @Kamikazilady 
As for users adding new rooms - needed or no for this target? We actually already have the POST call working but it requires users to have access. Which for now - not needed?

**Comment by Br3nda** [comment]
Is "user has access" a block somewhere?

**Comment by MeghanHughes** [comment]
How do you mean @Br3nda?

**Comment by Br3nda** [comment]
you said "it requires users to have access" <-- i'm trying to work out if you're asking for users that you don't have. Is this blocked?

**Comment by MeghanHughes** [comment]
Ah - no, I expected to be able to add rooms to my whare, but my req was returning a 401. 

Here's the request: 
```handleClick(event) {
    axios({
      method: "post",
      url: `https://app.wharehauora.nz/api/v1/rooms?access_token=${Cookies.get('token')}`,
      data: {
        data: {
          type: "rooms",
          attributes: {
            "name": this.state.name,
            "home-id": this.props.houseId
          }
        }
      },
      headers: {
        'Content-Type': 'application/vnd.api+json',
        'Accept': 'application/vnd.api+json'
      }
    })
  }
```

in `App/components/profile/setUp/AddRoomForm.js`

I wondered if users were allowed to POST a new room to the db

**Comment by Br3nda** [comment]
```2018-06-21T02:19:42.685435+00:00 app[web.1]: Internal Server Error: undefined method `owner_id' for nil:NilClass /app/app/policies/room_policy.rb:57:in `owner?'
2018-06-21T02:19:42.685437+00:00 app[web.1]: /app/app/policies/room_policy.rb:23:in `create?'
```

Looks like the policy is checking for owner in the wrong place. I'll look at it now.
