### ISSUE TITLE
Development branch no longer starts

### ISSUE THREAD

**Issue by Br3nda** [WhareHauora/App#170]
Someting changed today -- and now i can no longer get the `Development` branch to run `npm run dev`

Any ideas???
```
brenda@tui:~/projects/wharehauora-app$ node --version
v8.11.2
```
```
> whare-hauora@1.0.0 dev /home/brenda/projects/wharehauora-app
> concurrently --prefix '{time}:{name}' --names 'server,worker' --prefix-colors 'green,blue' --kill-others 'node server.js' 'node worker.js'

2018-06-19 14:04:40.633:worker /home/brenda/projects/wharehauora-app/node_modules/knex/lib/index.js:49
2018-06-19 14:04:40.633:worker   if (arguments.length === 0 || !config.client && !config.dialect) {
2018-06-19 14:04:40.633:worker                                         ^
2018-06-19 14:04:40.633:worker 
2018-06-19 14:04:40.633:worker TypeError: Cannot read property 'client' of undefined
2018-06-19 14:04:40.633:worker     at Knex (/home/brenda/projects/wharehauora-app/node_modules/knex/lib/index.js:49:41)
2018-06-19 14:04:40.633:worker     at Object.<anonymous> (/home/brenda/projects/wharehauora-app/db/knex.js:4:18)
2018-06-19 14:04:40.633:worker     at Module._compile (module.js:652:30)
2018-06-19 14:04:40.633:worker     at Object.Module._extensions..js (module.js:663:10)
2018-06-19 14:04:40.633:worker     at Module.load (module.js:565:32)
2018-06-19 14:04:40.633:worker     at tryModuleLoad (module.js:505:12)
2018-06-19 14:04:40.633:worker     at Function.Module._load (module.js:497:3)
2018-06-19 14:04:40.633:worker     at Module.require (module.js:596:17)
2018-06-19 14:04:40.633:worker     at require (internal/module.js:11:18)
2018-06-19 14:04:40.633:worker     at Object.<anonymous> (/home/brenda/projects/wharehauora-app/worker.js:6:12)
2018-06-19 14:04:40.633:worker     at Module._compile (module.js:652:30)
2018-06-19 14:04:40.633:worker     at Object.Module._extensions..js (module.js:663:10)
2018-06-19 14:04:40.633:worker     at Module.load (module.js:565:32)
2018-06-19 14:04:40.633:worker     at tryModuleLoad (module.js:505:12)
2018-06-19 14:04:40.633:worker     at Function.Module._load (module.js:497:3)
2018-06-19 14:04:40.633:worker     at Function.Module.runMain (module.js:693:10)
2018-06-19 14:04:40.641:worker node worker.js exited with code 1
--> Sending SIGTERM to other processes..
2018-06-19 14:04:40.675:server node server.js exited with code null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whare-hauora@1.0.0 dev: `concurrently --prefix '{time}:{name}' --names 'server,worker' --prefix-colors 'green,blue' --kill-others 'node server.js' 'node worker.js'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the whare-hauora@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/brenda/.npm/_logs/2018-06-19T02_04_40_683Z-debug.log
```

**Comment by MeghanHughes** [comment]
the vapid keys are in the .env file and are called in `worker.js` (which is just about to be reviewed in a pull request). 

"Use of VAPID for push requests is optional, but primarily a security benefit. Application servers use VAPID to identify themselves to the push servers so push subscriptions can be properly restricted to their origin app servers. In other words, VAPID could theoretically prevent an attacker from stealing a user PushSubscription and sending push messages to that recipient from another server. Down the road, push services may be able to provide analytics and debugging assistance for app servers using the VAPID protocol."

https://rossta.net/blog/using-the-web-push-api-with-vapid.html

**Comment by MeghanHughes** [comment]
There is a postgres database sitting between the app and Heroku which records who has enabled push notifications. This is so if the Ruby server goes down, or if there is an update, that data isn't lost (because it would sit client-side) and require all users to re-register. If the push notifications are triggered from the Ruby server (which I believe is what is expected in the longer run with it migrates to KAFKA?) then I don't believe we need the postgres database. 

The last set up of this notification strategy is just about to go into review for a PR

**Comment by MeghanHughes** [comment]
```const vapidPublicKey = 'BPCnADjDVFsexLnj6ESRHuu9YlDwg7P8b8k4_mi48LB8UDAYvTpAWYfBofUD8F9LWkh6U0dJqX0kCoF-yWb-tbM'
              const convertedVapidKey = urlBase64ToUint8Array(vapidPublicKey)
              function urlBase64ToUint8Array (base64String) {
                const padding = '='.repeat((4 - base64String.length % 4) % 4)
                const base64 = (base64String + padding).replace(/\-/g, '+').replace(/_/g, '/')
                const rawData = window.atob(base64)
                const outputArray = new Uint8Array(rawData.length)
                for (let i = 0; i < rawData.length; ++i) {
                  outputArray[i] = rawData.charCodeAt(i)
                }
```

This is the part in `pages/dashboard` that encodes the vapid key to a Uint8Array (this is what your error message refers to)

**Comment by Br3nda** [comment]
Sweet. So I just need to generate some keys according to that blog post. How about that goes in the README?

**Comment by MeghanHughes** [comment]
The keys are already generated and are in the .env - this is where we ran into trouble a little while ago when you pointed out we had our .env file hanging out in the repo. Now we are handing over to you, I will add the instructions for generating the keys and you can add new ones

**Comment by MeghanHughes** [comment]
I'll edit in a version of this https://github.com/web-push-libs/web-push
```
  web-push send-notification --endpoint=<url> [--key=<browser key>] [--auth=<auth secret>] [--payload=<message>] [--encoding=<aesgcm | aes128gcm>] [--ttl=<seconds>] [--vapid-subject=<vapid subject>] [--vapid-pubkey=<public key url base64>] [--vapid-pvtkey=<private key url base64>] [--gcm-api-key=<api key>]

  web-push generate-vapid-keys [--json]
```

**Comment by Br3nda** [comment]
it starts! :-D thanks.
